### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by wrightwriter**

### CODE REVIEW

**Comment by davidar** [comment]
Thanks! I'll just get CI setup first so we can test a staging build before merging

**Comment by davidar** [comment]
Hm, `codeHasBeenModified` seems to be interacting strangely with `manualReload` somehow, and is triggering the shader to recompile the first time I type a character in the code. We'll need to disentangle that a bit and do some more testing.

Otherwise LGTM

**Comment by wrightwriter** [comment]
Weird, i guess it's doing some DOM reloading which triggers the compile()?
Anyways - I'm just removing the codeHasBeenModified atom and replacing with useState. 👍

**Comment by wrightwriter** [comment]
This seems to work good for me!

**Comment by davidar** [comment]
The shader loading happens [here](https://github.com/compute-toys/compute.toys/blob/master/lib/db/dbrouter.ts), you might be able to hook into `dbLoadedAtom`?

**Comment by wrightwriter** [comment]
Ok yeah, that's what i thought, but i have no way to test it. I will write what i assume would work.

**Comment by davidar** [comment]
All looks good to me! Let me know when you're ready to merge and I'll setup a staging build

**Comment by wrightwriter** [comment]
Cool, I think it's ready!

**Pull request merged**
