### PR TITLE
Padding adjustments

### PR DESCRIPTION
**Pull request by wrightwriter**
Padding on header:
before - 
image
after - 
image
Timer padding:
before - 
image
after - 
image

### CODE REVIEW

**Comment by wrightwriter** [comment]
in MetadataEditor
before -
image
after -
image

**Comment by wrightwriter** [comment]
before: 
image
after:
image

**Comment by davidar** [comment]
I noticed an issue on smaller screens, but otherwise looks good

image

**Comment by wrightwriter** [comment]
i think i can fix this with `width` and `min-width`

**Comment by wrightwriter** [comment]
looks good to me like this. fixed the wrap issue.
https://github.com/compute-toys/compute.toys/assets/8731857/ece46726-a107-4376-9cae-6b548ba6edaa

**Pull request merged**
